services:
  backend:
    image: yy562198/quarkcine-backend:latest
    container_name: quarkcine-backend
    restart: unless-stopped
    ports:
      - "8009:8008"
    environment:
      - PORT=8008
      - TMDB_LANGUAGE=zh-CN
      - TZ=Asia/Shanghai
    volumes:
      - ./backend/data:/app/data

  frontend:
    image: yy562198/quarkcine-frontend:latest
    container_name: quarkcine-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
